### ISSUE TITLE
task: check tab order of various dialogs

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1997]
See also / needs #1971 

Approach:

1. remove tab focus of unneeded elements (such as the View (F4) / Markings checkboxes)
2. add tab focus where needed
2. use `SpaceCheckBox` for _important_ checkboxes (this can later be extended to _all_ checkboxes)
2. use `SpacePushButton` where needed
3. exclude tab focus for less important widgets, color pickers, "readonly" text/HTML panes
2. update tab order
3. set initial focus where needed
4. if possible, connect buddies (eg Surveys checkboxes)
4. (check that following didn't change:  dialog sizes, initial page focus)
3. include a reminder for GUI developers

## OK:
- [x] gui/shortcutsDialog.ui (#1971 ) (F7)
- [x] gui/configurationDialog.ui (F2)
- [x] gui/customDeltaTEquationDialog.ui (F2 > Time)

## Busy:
- [ ] gui/viewDialog.ui (F4)

## Keep for now...
- [ ] gui/obsListCreateEditDialog.ui (various open issues, which one?)
- [ ] gui/obsListDialog.ui (idem)
- [ ] gui/helpDialogGui.ui (F1) - ENTER triggers the bottom button

## Todo:

- [ ] gui/dateTimeDialogGui.ui (F5)
- [ ] gui/searchDialogGui.ui (F3)
- [ ] gui/locationDialogGui.ui (F6)

- [ ] gui/astroCalcDialog.ui (F10)
- [ ] gui/astroCalcCustomStepsDialog.ui
- [ ] gui/astroCalcExtraEphemerisDialog.ui

- [ ] gui/scriptConsole.ui

- [ ] gui/atmosphereDialog.ui
- [ ] gui/dsoColorsDialog.ui
- [ ] gui/orbitColorsDialog.ui
- [ ] gui/addRemoveLandscapesDialog.ui
- [ ] gui/greatRedSpotDialog.ui

Next: PR per UI (group).

Later iterations:
- Qt Designer custom widgets (https://doc.qt.io/qt-5/designer-creating-custom-widgets.html)

**Comment by axd1967** [comment]
@gzotti or @alex-w could you pls assign this issue to me? thx!
